import type { Event } from "./types"

export const mockEvents: Event[] = [
  {
    id: 1,
    title: "Urban Art Exhibition",
    description:
      "A showcase of contemporary urban artists featuring installations, murals, and interactive exhibits that explore city life and culture.",
    date: "2024-06-15",
    time: "10:00 AM - 6:00 PM",
    venue: "Modern Gallery",
    location: "Downtown",
    category: "Art",
    price: 0,
    image: "/placeholder.svg?height=400&width=600",
    featured: true,
    communityPick: true,
    votes: 45,
    organizer: "City Arts Collective",
    ticketUrl: "https://example.com/tickets/1",
  },
  {
    id: 2,
    title: "Jazz in the Park",
    description: "An evening of live jazz music featuring local musicians in a beautiful outdoor setting.",
    date: "2024-06-18",
    time: "7:00 PM - 10:00 PM",
    venue: "Central Park Amphitheater",
    location: "Midtown",
    category: "Music",
    price: 15,
    image: "/placeholder.svg?height=400&width=600",
    featured: true,
    votes: 32,
    organizer: "City Music Association",
    ticketUrl: "https://example.com/tickets/2",
  },
  {
    id: 3,
    title: "International Film Festival",
    description:
      "A week-long celebration of independent cinema from around the world, featuring screenings, director Q&As, and workshops.",
    date: "2024-06-20",
    time: "Various Times",
    venue: "Cinema Arts Center",
    location: "Downtown",
    category: "Film",
    price: 25,
    image: "/placeholder.svg?height=400&width=600",
    featured: true,
    communityPick: true,
    votes: 67,
    organizer: "Film Society",
    ticketUrl: "https://example.com/tickets/3",
  },
  {
    id: 4,
    title: "Cultural Food Festival",
    description:
      "Experience cuisines from around the world with food stalls, cooking demonstrations, and cultural performances.",
    date: "2024-06-25",
    time: "11:00 AM - 8:00 PM",
    venue: "Riverfront Plaza",
    location: "Downtown",
    category: "Food",
    price: 5,
    image: "/placeholder.svg?height=400&width=600",
    votes: 89,
    organizer: "Cultural Exchange Network",
    ticketUrl: "https://example.com/tickets/4",
  },
  {
    id: 5,
    title: "Contemporary Dance Performance",
    description: "A groundbreaking performance exploring themes of identity and connection through modern dance.",
    date: "2024-06-28",
    time: "8:00 PM - 10:00 PM",
    venue: "City Theater",
    location: "Uptown",
    category: "Dance",
    price: 30,
    image: "/placeholder.svg?height=400&width=600",
    communityPick: true,
    votes: 23,
    organizer: "Modern Dance Company",
    ticketUrl: "https://example.com/tickets/5",
  },
  {
    id: 6,
    title: "Literary Evening with Author",
    description: "Join acclaimed author for a reading and discussion of their latest work.",
    date: "2024-07-02",
    time: "6:30 PM - 8:30 PM",
    venue: "Central Library",
    location: "Midtown",
    category: "Literature",
    price: 0,
    image: "/placeholder.svg?height=400&width=600",
    votes: 18,
    organizer: "City Literary Society",
  },
  {
    id: 7,
    title: "Street Art Workshop",
    description:
      "Learn techniques from professional street artists and create your own piece in this hands-on workshop.",
    date: "2024-07-05",
    time: "2:00 PM - 5:00 PM",
    venue: "Community Arts Center",
    location: "West Side",
    category: "Workshop",
    price: 25,
    image: "/placeholder.svg?height=400&width=600",
    votes: 15,
    organizer: "Urban Arts Initiative",
    ticketUrl: "https://example.com/tickets/7",
  },
  {
    id: 8,
    title: "Classical Music Concert",
    description: "The city symphony orchestra performs masterpieces from Mozart, Beethoven, and Tchaikovsky.",
    date: "2024-07-08",
    time: "7:30 PM - 9:30 PM",
    venue: "Concert Hall",
    location: "Downtown",
    category: "Music",
    price: 40,
    image: "/placeholder.svg?height=400&width=600",
    votes: 42,
    organizer: "City Symphony",
    ticketUrl: "https://example.com/tickets/8",
  },
  {
    id: 9,
    title: "Photography Exhibition",
    description: "A collection of stunning photographs capturing urban life and natural landscapes.",
    date: "2024-07-10",
    time: "10:00 AM - 5:00 PM",
    venue: "Photography Museum",
    location: "East Side",
    category: "Art",
    price: 10,
    image: "/placeholder.svg?height=400&width=600",
    votes: 29,
    organizer: "Photographers Association",
    ticketUrl: "https://example.com/tickets/9",
  },
  {
    id: 10,
    title: "Indie Music Festival",
    description: "A day-long festival featuring independent musicians across multiple genres.",
    date: "2024-07-15",
    time: "12:00 PM - 11:00 PM",
    venue: "Riverside Park",
    location: "West Side",
    category: "Music",
    price: 35,
    image: "/placeholder.svg?height=400&width=600",
    communityPick: true,
    votes: 76,
    organizer: "Independent Music Collective",
    ticketUrl: "https://example.com/tickets/10",
  },
  {
    id: 11,
    title: "Theater in the Round",
    description: "An immersive theatrical experience where the audience surrounds the performers.",
    date: "2024-07-18",
    time: "8:00 PM - 10:00 PM",
    venue: "Experimental Theater",
    location: "Downtown",
    category: "Theater",
    price: 25,
    image: "/placeholder.svg?height=400&width=600",
    votes: 31,
    organizer: "Avant-Garde Theater Company",
    ticketUrl: "https://example.com/tickets/11",
  },
  {
    id: 12,
    title: "Cultural Heritage Festival",
    description: "Celebrate the diverse cultural heritage of our city with performances, crafts, and food.",
    date: "2024-07-22",
    time: "11:00 AM - 7:00 PM",
    venue: "Cultural Center",
    location: "Midtown",
    category: "Festival",
    price: 0,
    image: "/placeholder.svg?height=400&width=600",
    featured: true,
    votes: 54,
    organizer: "Cultural Heritage Foundation",
  },
]
